version: "3.2"
services:
  app:
    container_name: sonos-pi-touch
    restart: always
    privileged: true
    network_mode: 'host'
    build: .
    image: bytegenesis/sonos-pi-touch
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - '/sys/class/backlight:/sys/class/backlight'
    devices:
      - "/dev/fb1:/dev/fb1"      
