FROM arm32v5/debian

RUN apt-get update && apt-get install -y python-pygame python-pip
RUN easy_install -U distribute && apt-get install -y git && pip install -e git+https://github.com/Villarrealized/pygameui.git@master#egg=pygameui
